#!/bin/sh

#
# Weird ibus stuff for IntelliJ
#
# See: https://youtrack.jetbrains.com/issue/IDEA-78860
#

which ibus &> /dev/null
if [ $? -ne 0 ]; then
    # Should be okay!
    echo > /dev/null
else
    IBUS=`ibus version 2> /dev/null | sed -e 's/\([0-9][0-9]*\)/00\1/g'`
    # If version is too old...
    if [ "$IBUS" \< "IBus 001.005.011" ]; then
        export IBUS_ENABLE_SYNC_MODE=1
    fi
fi
