#!/usr/bin/env zsh
#
# Grab/update the repo
#

moduledir="${1:-${0:a:h}}"
generated="${2:-/dev/null}"

loadrepo() {
    local repodir="$1"
    local repo="$2"

    # See if we're already installed
    if [ -d "${moduledir}/dotfiles/i3/${repodir}" ]; then
        # Assume the repo exists, update it
        ( cd "${moduledir}/dotfiles/i3/${repodir}" && git pull -q --recurse-submodules ) || carapace-message "red" "Failed to update repo: $repodir"
    else
        # Assume the repo does not exist
        ( cd "${moduledir}/dotfiles/i3" && git clone --recurse-submodules "${repo}" ./${repodir} ) || carapace-message "red" "Failed to load repo: $repo"

        return $?
    fi
}

loadrepo "bumblebee-status" "https://github.com/tobi-wan-kenobi/bumblebee-status.git"

# Link my modules into the bumblebee folder
beerepo="${moduledir}/dotfiles/i3/bumblebee-status"
beemoddir="${moduledir}/carapace-bee/modules"
beethemedir="${moduledir}/carapace-bee/themes"

if [ -d "$beerepo" ]; then
    if [ -d "$beemoddir" -a -n "$(ls -A "$beemoddir"/*.py 2> /dev/null)" ]; then
        for i in $beemoddir/*.py; do
            carapace-redirect "$i" "${beerepo}/bumblebee/modules/${i:t}"
        done
    fi
    if [ -d "$beethemedir" -a -n "$(ls -A "$beethemedir"/*.json 2> /dev/null)" ]; then
        for i in $beethemedir/*.json; do
            carapace-redirect "$i" "${beerepo}/themes/${i:t}"
        done
    fi
fi

