#!/usr/bin/env zsh
#
# Run at i3 startup
#

# Black background
xsetroot -solid '#000000' &

# Turn on numlock
numlockx on &

# Put an image on the background
setbgimage

# Disable tap-to-click on the touchpad
disable-touchpad-click

# Turn on screen blanking
xset dpms 900 1200 1500
xset +dpms

# Set up screensaver
xautolock -detectsleep -time 10 -locker "$HOME/bin/carapace/lock" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'About to lock screen!'" &

